# The URL the site will be built for
base_url = "https://sinon.github.io"
default_language = "en"
title = "Rob's Blog | Python • Rust • Ramblings?"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
generate_feeds = true
feed_filenames = ["rss.xml"]

theme = "after-dark"

taxonomies = [{ name = "tags", feed = true }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "axar"
render_emoji = true

[extra]
author = "Rob Hand"
codeblock = true
after_dark_menu = [
  { name = "Home", url = "$BASE_URL" },
  { name = "Tags", url = "$BASE_URL/tags" },
  { name = "Source", url = "https://github.com/Sinon/sinon.github.io" },
  { name = "GitHub", url = "https://github.com/Sinon" },
  { name = "CV", url = "https://raw.githubusercontent.com/sinon/CV/main/cv.pdf" },
  { name = "RSS", url = "$BASE_URL/rss.xml" },
]
after_dark_title = "Rob's Blog | Python • Rust • Ramblings?"
